// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBfdnFzNsI0QcSFFlKQVEC3GETp8hX7Jc',
    appId: '1:396311842463:android:66ccf17d79e3d33748dcaa',
    messagingSenderId: '396311842463',
    projectId: 'control-asistencia-tfg-jrm',
    storageBucket: 'control-asistencia-tfg-jrm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqEV_Y7PcAz3WmJaROL6aGaR5vHjfoAb0',
    appId: '1:396311842463:ios:132113d22688ec5548dcaa',
    messagingSenderId: '396311842463',
    projectId: 'control-asistencia-tfg-jrm',
    storageBucket: 'control-asistencia-tfg-jrm.appspot.com',
    iosClientId: '396311842463-5ed499kjv68mufvjj3ls19lp6ct8bd64.apps.googleusercontent.com',
    iosBundleId: 'com.example.controlAsistenciaTfgJrm',
  );
}
